#!/bin/bash
# DB에서 기존 test@example.com 계정을 삭제하고 앱 재시작 시 새로 생성되도록 함

echo "========================================"
echo "테스트 계정 비밀번호 업데이트 가이드"
echo "========================================"
echo ""
echo "DB 접속 정보를 application-local.yml에서 확인하세요."
echo ""
echo "방법 1 (권장): 기존 계정 삭제 후 앱 재시작"
echo "--------------------------------------"
echo "1. DB 접속:"
echo "   psql -h <DB_HOST> -U dbmasteruser -d ga_db"
echo ""
echo "2. 기존 계정 삭제:"
echo "   DELETE FROM users WHERE email = 'test@example.com';"
echo ""
echo "3. 앱 재시작 (local 프로파일):"
echo "   ./gradlew bootRun --args='--spring.profiles.active=local'"
echo ""
echo "4. TestUserSeeder가 자동으로 test@example.com / test1234Z 계정 생성"
echo ""
echo "========================================"
echo ""
echo "방법 2: 앱 재시작만 (계정이 없을 경우)"
echo "--------------------------------------"
echo "test@example.com 계정이 DB에 없다면,"
echo "앱 재시작만으로 자동 생성됩니다:"
echo "   ./gradlew bootRun --args='--spring.profiles.active=local'"
echo ""
echo "========================================"
