#!/bin/bash
# 서비스별 API 문서 로드 오류 진단 스크립트

echo "=========================================="
echo "서비스 상태 진단 시작"
echo "=========================================="
echo ""

echo "1. Docker 컨테이너 상태 확인"
echo "----------------------------------------"
docker ps -a | grep -E "ga-auth-service|ga-user-service|ga-audit-service|ga-ai-consultant-service|ga-matching-service"
echo ""

echo "2. 포트 리스닝 상태 확인"
echo "----------------------------------------"
netstat -tlnp 2>/dev/null | grep -E "8081|8082|8083|8084|8085" || ss -tlnp 2>/dev/null | grep -E "8081|8082|8083|8084|8085"
echo ""

echo "3. Auth Service 직접 접근 테스트 (500 에러 확인)"
echo "----------------------------------------"
echo "Health check:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8081/actuator/health || echo "연결 실패"
echo ""
echo "API docs:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8081/v3/api-docs || echo "연결 실패"
echo ""

echo "4. User Service 직접 접근 테스트 (502 에러 확인)"
echo "----------------------------------------"
echo "Health check:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8082/actuator/health || echo "연결 실패"
echo ""
echo "API docs:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8082/v3/api-docs || echo "연결 실패"
echo ""

echo "5. Audit Service 직접 접근 테스트 (502 에러 확인)"
echo "----------------------------------------"
echo "Health check:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8083/actuator/health || echo "연결 실패"
echo ""
echo "API docs:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8083/v3/api-docs || echo "연결 실패"
echo ""

echo "6. AI Consultant Service 직접 접근 테스트 (502 에러 확인)"
echo "----------------------------------------"
echo "Health check:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8084/actuator/health || echo "연결 실패"
echo ""
echo "API docs:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8084/v3/api-docs || echo "연결 실패"
echo ""

echo "7. Matching Service 직접 접근 테스트 (무한 로딩 확인)"
echo "----------------------------------------"
echo "Health check:"
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8085/actuator/health || echo "연결 실패"
echo ""
echo "API docs (30초 타임아웃):"
timeout 30 curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://127.0.0.1:8085/v3/api-docs || echo "타임아웃 또는 연결 실패"
echo ""

echo "8. nginx 에러 로그 확인 (최근 50줄)"
echo "----------------------------------------"
sudo tail -n 50 /var/log/nginx/error.log | grep -E "v3/api-docs|502|500" || echo "관련 에러 없음"
echo ""

echo "=========================================="
echo "진단 완료"
echo "=========================================="
echo ""
echo "다음 단계:"
echo "1. 서비스 로그 확인: docker logs <service-name> --tail 100"
echo "2. 문제가 있는 서비스 재시작: docker restart <service-name>"
echo "3. 모든 서비스 재시작: docker-compose restart"
